version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    restart: always
    shm_size: 2gb
  spidy:
    build:
      context: .
    depends_on:
      - selenium
    restart: always